coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        informational: true
    patch:
      default:
        target: auto
        threshold: 0%
        informational: true

# do not include tests folders
ignore:
  - "tests"
  - "plugins/metrics/config_test.go"
  - "plugins/websockets/storage/storage_test.go"
  - "plugins/websockets/config.go"
  - "pkg/bst/bst_test.go"
  - "pkg/doc"
  - "pkg/pool/static_pool_test.go"
  - "pkg/pool/supervisor_test.go"
  - "pkg/pubsub"
  - "pkg/transport/pipe/pipe_factory_spawn_test.go"
  - "pkg/transport/pipe/pipe_factory_test.go"
  - "pkg/transport/socket/socket_factory_spawn_test.go"
  - "pkg/transport/socket/socket_factory_test.go"
  - "pkg/transport/interface.go"
  - "pkg/worker/state_test.go"
  - "pkg/worker/sync_worker_test.go"
  - "pkg/worker/worker_test.go"
  - "pkg/events/pool_events.go"
  - "pkg/events/worker_events.go"
  - "systemd"
